<?php

namespace Modules\Pebblely\Database\Seeders\versions\v5_2_0;

use Illuminate\Database\Seeder;

use \Modules\OpenAI\Entities\ProductBackground;

class ProductBackgroundsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('product_backgrounds')->delete();
        
        ProductBackground::upsert([
            [
                'user_id' => 1,
                'name' => 'Studio',
                'background_id' => 'studio',
                'file_url' => 'https://pebblely.b-cdn.net/samples/pebblely%20-%202023-03-17T164517.910.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Silk',
                'background_id' => 'silk',
                'file_url' => 'https://pebblely.b-cdn.net/samples/pebblely%20-%202023-03-18T161959.621.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Cafe',
                'background_id' => 'cafe',
                'file_url' => 'https://pebblely.b-cdn.net/samples/sample_20221226_015008_22.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Tabletop',
                'background_id' => 'tabletop',
                'file_url' => 'https://pebblely.b-cdn.net/samples/pebblely%20-%202023-03-17T160622.039.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Marble',
                'background_id' => 'marble',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-marble.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Outdoors',
                'background_id' => 'outdoors',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-outdoors.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Flowers',
                'background_id' => 'flowers',
                'file_url' => 'https://pebblely.b-cdn.net/samples/sample_20221226_013124_10.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Roses',
                'background_id' => 'roses',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-roses.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Lavender',
                'background_id' => 'lavender',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-lavender.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Monstera',
                'background_id' => 'monstera',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-monstera.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Meadow',
                'background_id' => 'meadow',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-meadow.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Kitchen',
                'background_id' => 'kitchen',
                'file_url' => 'https://pebblely.b-cdn.net/samples/sample_20230130_111500_1.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Fruits',
                'background_id' => 'fruits',
                'file_url' => 'https://pebblely.b-cdn.net/samples/sample_20221226_013404_15.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Nature',
                'background_id' => 'nature',
                'file_url' => 'https://pebblely.b-cdn.net/samples/sample_20221226_013645_20.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Beach',
                'background_id' => 'beach',
                'file_url' => 'https://pebblely.b-cdn.net/samples/sample_20221226_015530_43.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ], 
            [
                'user_id' => 1,
                'name' => 'Bathroom',
                'background_id' => 'bathroom',
                'file_url' => 'https://pebblely.b-cdn.net/samples/sample_20230204_1600_1.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Skyscraper',
                'background_id' => 'skyscraper',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-skyscraper.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Gifts',
                'background_id' => 'gifts',
                'file_url' => 'https://pebblely.b-cdn.net/samples/gifts_sample.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Christmas',
                'background_id' => 'christmas',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-christmas.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Wedding',
                'background_id' => 'wedding',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-wedding.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Halloween',
                'background_id' => 'halloween',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-halloween.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Easter',
                'background_id' => 'easter',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-easter-2.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Paint',
                'background_id' => 'paint',
                'file_url' => 'https://pebblely.b-cdn.net/samples/sample_20221226_013926_38.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Fire',
                'background_id' => 'fire',
                'file_url' => 'https://pebblely.b-cdn.net/samples/fire_sample.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Water',
                'background_id' => 'water',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-water.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Gold',
                'background_id' => 'gold',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-gold.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Pebbles',
                'background_id' => 'pebbles',
                'file_url' => 'https://pebblely.b-cdn.net/samples/sample_20221226_015811_32.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Snow',
                'background_id' => 'snow',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-snow.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Necklace',
                'background_id' => 'necklace',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-necklace.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Furniture',
                'background_id' => 'furniture',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-modern.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Surprise me',
                'background_id' => 'surprise-me',
                'file_url' => 'https://pebblely.b-cdn.net/samples/surprise-me.png',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Light Wood',
                'background_id' => 'light-wood',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-light-wood.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Dark Wood',
                'background_id' => 'dark-wood',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-dark-wood.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Park Bench',
                'background_id' => 'park-bench',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-park-bench.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Dried Flowers',
                'background_id' => 'dried-flowers',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-dried-flowers.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Baby\'s Breath',
                'background_id' => 'babys-breath',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-babys-breath.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Modern Interior',
                'background_id' => 'modern-interior',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-modern.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Minimalist Interior',
                'background_id' => 'minimalist-interior',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-minimalist.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Japanese Interior',
                'background_id' => 'japanese-interior',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-japanese.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Scandi Interior',
                'background_id' => 'scandi-interior',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-scandi.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Luxury Interior',
                'background_id' => 'luxury-interior',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-luxury.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Coastal Interior',
                'background_id' => 'coastal-interior',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-coastal.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Bohemian Interior',
                'background_id' => 'bohemian-interior',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-bohemian.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
            [
                'user_id' => 1,
                'name' => 'Farmhouse Interior',
                'background_id' => 'farmhouse-interior',
                'file_url' => 'https://pebblely.b-cdn.net/samples/thumbnail-farmhouse.jpg',
                'type' => 'ai_product_photography',
                'status' => 'Active',
                'provider' => 'pebblely',
            ],
        ], ['background_id'], [ 'background_id','user_id','name','file_url','type','status','provider']);
        
        
    }
}